services:
  backend:
    build:
      context: ./backend

    container_name: ai-backend

    ports:
      - "8000:8080"

    volumes:
      - ./backend/db:/app/db

    env_file:
      - ./backend/.env

  frontend:
    build:
      context: ./frontend

    container_name: ai-frontend

    ports:
      - "8501:8080"

    environment:
      - API_URL=http://backend:8080

    depends_on:
      - backend